### ISSUE TITLE
missing dependency on npm (at least jessie)

### ISSUE THREAD

**Issue by mhaberler** [rcn-ee/repos#8]
maybe add to https://github.com/rcn-ee/repos/blob/master/bb-npm-installer/suite/jessie/debian/control?

causes omap-image-builder to keel over on bb-npm-installer
`````
Setting up tmux (1.9-6) ...
Setting up bb-npm-installer (3.8.2-0rcnee1~bpo80+20160321+1) ...

module.js:340
    throw err;
          ^
Error: Cannot find module '/usr/bin/npm'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
bb-npm-installer:npm: []
bb-npm-installer:node: [v0.10.42]

module.js:340
    throw err;
          ^
Error: Cannot find module '/usr/bin/npm'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
dpkg: error processing package bb-npm-installer (--configure):
 subprocess installed post-installation script returned error exit status 8
Processing triggers for libc-bin (2.19-18+deb8u4) ...
Errors were encountered while processing:
 bb-npm-installer
E: Sub-process /usr/bin/dpkg returned an error code (1)
`````

**Comment by RobertCNelson** [comment]
In debian, nodejs, is split up into nodejs/nodejs-legacy/nodejs-dev/npm, we've switched to nodesource, so we can slowlly move from v0.10.x -> latest more easily.. However there "nodejs" package as everything, so it isn't split up as debian's..

Regards,
